version: '3'

# A setup for bootstraping more than one different SQL db server instances
services: 

    mariadb:
        image: mariadb:10.2
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports: 
            - "3306:3306"
        volumes:
            - ${MYSQL_LOCAL_DATA}:/var/lib/mysql/
    postgres:
        image: postgres:12.1-alpine
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports: 
            - "54321:5432"    
        volumes: 
            - pgdata:/var/lib/postgresql/data/

volumes: 
    mariadb:
    pgdata:
    