version: '3.7'

networks: 
    dockerap-dev:
        driver: bridge

services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        command: 
            sh -c "dotnet run"
    db: 
        image: postgres:12.1-alpine
        ports: 
            - "54321:5432"
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes: 
            - "${PG_LOCAL_DATA}:${PG_DOCKER_DATA}"