version: '3'

services:
    php-apache:
        image: php:7.2.1-apache
        ports:
            - 80:80
        volumes:
            - ./MyProject:/var/www/html

    mysql:
        image: mysql:latest
        volumes:
            - C:\Users\Dana\Documents\Dev\mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            TZ: "America/Vancouver"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes:
    mysql: