version: '3'

services:
    php-apache:
        image: php:7.2.1-apache
        ports:
            - 80:80
        volumes:
            - ./MyProject:/var/www/html

    mariadb:
        image: mariadb:10.2
        volumes:
            - ${MARIADB_VOLUME}:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            TZ: "America/Vancouver"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: {MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
    mariadb: