version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
    depends_on: 
      - 'db' 

  db: 
    image: postgres:12.1-alpine
    ports: 
      - "54321:5432"
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes: 
    pgdata:
