version: '3'

services:

    webserver:
        image: puckel/docker-airflow:1.10.7

    postgres:
        image: postgres:12.1-alpine
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports: 
            - "54321:5432"    
        volumes: 
            - pgdata:/var/lib/postgresql/data/

    scheduler:
        

volumes: 
    pgdata: